//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _073_ClienteConsole.ProxyPessoaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://schemas.datacontract.org/2004/07/_073_PessoaWCF")]
    [System.SerializableAttribute()]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FumanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Fumante {
            get {
                return this.FumanteField;
            }
            set {
                if ((this.FumanteField.Equals(value) != true)) {
                    this.FumanteField = value;
                    this.RaisePropertyChanged("Fumante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPessoaService.IPessoaService")]
    public interface IPessoaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPessoaService/Get", ReplyAction="http://tempuri.org/IPessoaService/GetResponse")]
        _073_ClienteConsole.ProxyPessoaService.Pessoa[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPessoaService/Get", ReplyAction="http://tempuri.org/IPessoaService/GetResponse")]
        System.Threading.Tasks.Task<_073_ClienteConsole.ProxyPessoaService.Pessoa[]> GetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPessoaServiceChannel : _073_ClienteConsole.ProxyPessoaService.IPessoaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PessoaServiceClient : System.ServiceModel.ClientBase<_073_ClienteConsole.ProxyPessoaService.IPessoaService>, _073_ClienteConsole.ProxyPessoaService.IPessoaService {
        
        public PessoaServiceClient() {
        }
        
        public PessoaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PessoaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _073_ClienteConsole.ProxyPessoaService.Pessoa[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<_073_ClienteConsole.ProxyPessoaService.Pessoa[]> GetAsync() {
            return base.Channel.GetAsync();
        }
    }
}
